# # Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hibernate
      POSTGRES_PASSWORD: hibernate
      POSTGRES_DB: quarkus

  mysql:
    image: mysql:latest
    container_name: mysql-teste
    environment:
      MYSQL_ROOT_PASSWORD: hibernate
      MYSQL_DATABASE: quarkus
      MYSQL_USER: hibernate
      MYSQL_PASSWORD: hibernate
    ports:
      - 3306:3306
  
  front:
    image: leogoandete/doasanguepoa-front:v1.2.0
    container_name: front
    ports:
      - 3000:3000
    environment:
      - REACT_APP_URL_API_LOGIN=http://localhost:8080